services:
  fdua-competition:
    build:
      context: .
    container_name: fdua-competition
    volumes:
      - .:/fdua-competition
    tty: true
    env_file:
      - secrets/.env

  fdua-notebook:
    build:
      context: .
    container_name: fdua-notebook
    volumes:
      - .:/fdua-competition
    tty: true
    command: uv run jupyter lab --ip 0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token=''
    ports:
      - "8888:8888"
    env_file:
      - secrets/.env